export const TYPES = {
  ADD_TO_CART: 'ADD_TO_CART',
  INCREMENT_TO_CART: 'INCREMENT_TO_CART',
  DECREMENT_TO_CART: 'DECREMENT_TO_CART',
  DELETE_FROM_CART: 'DELETE_FROM_CART',
  CLEAR_CART: 'CLEAR_CART'
}
